version: '3.7'

services:
  back:
    build:
      context: back
      dockerfile: ../buildfiles/back.dockerfile
      target: development
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      SECRET_TOKEN: '${SECRET_TOKEN}'
    volumes:
      - ./back/src:/app/src
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - './data/db:/var/lib/pgdata/data'
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      TZ: 'Asia/Vladivostok'

  front:
    build:
      context: ./front
      dockerfile: ../buildfiles/front.dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - './front/src:/app/src'

networks:
  bot:
    driver: bridge
