name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t my-gh-pages .
      
    - name: Run container and copy files
      run: |
        mkdir -p ./dist
        docker run --rm -v $(pwd)/dist:/output my-gh-pages sh -c "cp -r /usr/share/nginx/html/* /output"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
